const {JSDOM}=require('jsdom'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'../app/src/main/assets');
const dom=new JSDOM(fs.readFileSync(path.join(root,'index.html'),'utf8'),{url:'https://app.starlight.local/',runScripts:'outside-only'}),w=dom.window;
const frames=new Map();let seq=0,hidden=false,observer;
w.requestAnimationFrame=fn=>{frames.set(++seq,fn);return seq;};w.cancelAnimationFrame=id=>frames.delete(id);w.setInterval=()=>{};
Object.defineProperty(w.document,'hidden',{get:()=>hidden});
w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};
w.HTMLCanvasElement.prototype.getContext=()=>new Proxy({createLinearGradient:()=>({addColorStop(){}}),createRadialGradient:()=>({addColorStop(){}}),measureText:t=>({width:t.length*10})},{get:(o,k)=>k in o?o[k]:()=>{}});
const preference={matches:false,listeners:new Set(),addEventListener(_,fn){this.listeners.add(fn);},removeEventListener(_,fn){this.listeners.delete(fn);}};w.matchMedia=()=>preference;
w.IntersectionObserver=class {constructor(fn){observer=this;this.callback=fn;}observe(){}disconnect(){this.disconnected=true;}};
for(const script of w.document.querySelectorAll('script[src]'))vm.runInContext(fs.readFileSync(path.join(root,script.getAttribute('src')),'utf8'),dom.getInternalVMContext());
frames.clear(); // The chart loop is outside this focused viewer lifecycle test.
let latestImage,autoLoad=true,projections=0,loop,lastView;
w.Image=class {constructor(){latestImage=this;}set src(value){this.source=value;if(value&&autoLoad)this.onload?.();}};
w.SkyMoonSurface.draw=(_,__,___,view)=>{projections++;lastView={...view};};
const originalMotion=w.SkySunSurface.motion;w.SkySunSurface.motion=(...args)=>{loop=originalMotion(...args);return loop;};
const run=s=>vm.runInContext(s,dom.getInternalVMContext()),body=()=>w.document.getElementById('sheetBody');
const click=t=>{const btn=[...body().querySelectorAll('button')].find(b=>b.textContent===t);assert(btn,t);btn.click();};
const tick=t=>{const batch=[...frames];for(const [id,fn] of batch){if(frames.delete(id))fn(t);}};
run('showSunSurface()');assert(loop.active);assert(w.document.getElementById('sheet').classList.contains('surface-sheet'));run('dirty=true;render()');assert(run('dirty'),'covered chart does not redraw');tick(0);const base=projections;
for(let t=17;t<=1000;t+=17)tick(t);assert.equal(projections,base,'live overlay uses one surface');
click('暂停动态效果');assert(!loop.active);tick(1010);assert.equal(frames.size,0);const held=loop.time;
click('播放动态效果');tick(5000);assert.equal(loop.time,held);assert(loop.active);
click('隐藏光晕');assert(!loop.active);tick(5010);assert.equal(frames.size,0);click('显示光晕');assert(loop.active);
const canvas=body().querySelector('canvas');canvas.onpointerdown({pointerId:1,clientX:100,clientY:100,preventDefault(){}});assert(!loop.active);
canvas.onpointermove({pointerId:1,clientX:140,clientY:120});tick(5020);assert.equal(canvas.width,256);
canvas.onpointerup({pointerId:1});tick(5030);assert(canvas.width>=512);assert(loop.active);
run('nativeAppPaused()');assert(!loop.active);assert.equal(frames.size,0);const pausedProjection=projections;
run('nativeAppResumed()');tick(10000);assert(loop.active);assert.equal(projections,pausedProjection+1,'resume rebuilds the released surface');
hidden=true;w.document.dispatchEvent(new w.Event('visibilitychange'));assert(!loop.active);assert.equal(frames.size,0);
hidden=false;w.document.dispatchEvent(new w.Event('visibilitychange'));tick(11000);assert(loop.active);
observer.callback([{isIntersecting:false}]);assert(!loop.active);observer.callback([{isIntersecting:true}]);assert(loop.active);
for(let i=0;i<4;i++)click('＋');assert(!loop.active,'fully zoomed sphere has no visible animated limb');tick(11010);click('复位');assert(loop.active);tick(11020);
preference.matches=true;for(const fn of preference.listeners)fn();assert(!loop.active);assert(body().textContent.includes('动态已暂停'));tick(11030);
run('cleanupSheet()');assert(!loop.active);assert.equal(frames.size,0);assert.equal(canvas.width,0);assert.equal(latestImage.source,'');assert.equal(latestImage.onload,null);assert(observer.disconnected);assert.equal(preference.listeners.size,0);assert(!w.document.getElementById('sheet').classList.contains('surface-sheet'));
canvas.onwheel({deltaY:-1,preventDefault(){}});assert.equal(frames.size,0,'detached handlers cannot restart drawing');
run('showSunSurface()');assert(!loop.active,'system reduced motion disables autoplay');tick(12000);click('播放动态效果');assert(loop.active,'explicit playback is available');
run('showMoonSurface()');assert(!loop.active);assert.equal(preference.listeners.size,0);tick(12010);
let menu=body().querySelector('#moonFeature');assert.equal(menu.options.length,41);
menu.value='6163';menu.dispatchEvent(new w.Event('change'));tick(12020);
assert.equal(lastView.yaw,-11.22);assert.equal(lastView.pitch,-43.30);assert.equal(lastView.zoom,2);assert(lastView.inspect);assert(body().textContent.includes('85.29 km'));
menu.value='';menu.dispatchEvent(new w.Event('change'));tick(12030);
const moon=body().querySelector('canvas');moon.getBoundingClientRect=()=>({left:0,top:0,width:320,height:320});
const pointer=id=>({pointerId:id,clientX:160,clientY:160,preventDefault(){}});
moon.onpointerdown(pointer(1));moon.onpointerup(pointer(1));tick(12040);assert.equal(menu.value,'6163','tap selects the projected center');
menu.value='';menu.dispatchEvent(new w.Event('change'));tick(12050);
moon.onpointerdown(pointer(1));moon.onpointercancel(pointer(1));tick(12060);assert.equal(menu.value,'','cancel cannot select');
moon.onpointerdown(pointer(1));moon.onpointerdown(pointer(2));moon.onpointerup(pointer(2));moon.onpointerup(pointer(1));tick(12070);assert.equal(menu.value,'','two-pointer gesture cannot select');
click('隐藏地形标注');tick(12080);moon.onpointerdown(pointer(1));moon.onpointerup(pointer(1));tick(12090);assert.equal(menu.value,'','hidden markers cannot select');
click('显示地形标注');tick(12100);moon.onpointerdown(pointer(1));moon.onpointerup(pointer(1));tick(12110);assert.equal(menu.value,'6163');
click('复位');tick(12120);assert.equal(menu.value,'');assert.equal(lastView.zoom,1);run('cleanupSheet()');assert.equal(frames.size,0);
autoLoad=false;run('showSunSurface()');assert(!loop.active);assert([...body().querySelectorAll('.moon-controls button')].every(b=>b.disabled));
latestImage.onerror();assert(body().textContent.includes('纹理加载失败'));assert.equal(frames.size,0);run('cleanupSheet()');
dom.window.close();console.log('PASS: solar playback, glow, touch resolution, zoom, native/visibility pause, offscreen stop, reduced motion, close/switch disposal and failed texture lifecycle.');
