// DOM-level smoke test. No actual rendering, Android sensors or browser emulation.
const {JSDOM}=require('jsdom'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'../app/src/main/assets');
const dom=new JSDOM(fs.readFileSync(path.join(root,'index.html'),'utf8'),{url:'https://app.starlight.local/',runScripts:'outside-only'});
const w=dom.window;
w.HTMLCanvasElement.prototype.getContext=()=>new Proxy({createLinearGradient:()=>({addColorStop(){}}),createRadialGradient:()=>({addColorStop(){}}),measureText:t=>({width:t.length*10})},{get:(o,k)=>k in o?o[k]:()=>{}});
w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};
w.requestAnimationFrame=()=>{};w.setInterval=()=>{};
for(const f of ['astronomy.js',...fs.readdirSync(root).filter(f=>/^stars-\d+\.js$/.test(f)).sort(),'messier.js','constellations.js','core.js','visual.js','backup.js','planner.js','app.js'])require('node:vm').runInContext(fs.readFileSync(path.join(root,f),'utf8'),dom.getInternalVMContext());
const click=id=>w.document.getElementById(id).click(),body=()=>w.document.getElementById('sheetBody'),text=()=>body().textContent;
function clickText(t){const b=[...body().querySelectorAll('button')].find(x=>x.textContent===t);assert(b,t);b.click();}
click('search');let search=body().querySelector('input');search.value='天狼星';search.dispatchEvent(new w.Event('input'));assert(text().includes('天狼星'));clickText('查看');assert(text().includes('光年'));body().querySelector('textarea').value='测试笔记';clickText('收藏并保存笔记');click('saved');assert(text().includes('天狼星'));
click('search');search=body().querySelector('input');search.value='M31';search.dispatchEvent(new w.Event('input'));assert(text().includes('仙女座星系'));clickText('查看');assert(text().includes('目录总星等'));assert(text().includes('NGC 224'));assert(text().includes('未收录'));click('search');search=body().querySelector('input');search.value='NGC1976';search.dispatchEvent(new w.Event('input'));assert(text().includes('猎户座大星云'));click('search');clickText('浏览梅西耶 110');assert.equal(body().querySelectorAll('.row').length,110);
click('search');clickText('浏览 88 星座');assert.equal(body().querySelectorAll('.row').length,88);
click('search');search=body().querySelector('input');search.value='六分';search.dispatchEvent(new w.Event('input'));assert(text().includes('六分儀座'));clickText('查看');assert(text().includes('没有收录连线'));clickText('在星图中定位');assert.equal(require('node:vm').runInContext('selected.id',dom.getInternalVMContext()),'conSex');
click('search');search=body().querySelector('input');search.value='巨蛇座';search.dispatchEvent(new w.Event('input'));assert.equal([...body().querySelectorAll('.row b')].filter(x=>x.textContent==='巨蛇座').length,1);
click('loc');let inputs=body().querySelectorAll('input');inputs[0].value='91';inputs[1].value='0';clickText('保存位置');assert(w.document.getElementById('toast').textContent.includes('有效纬度'));inputs[0].value='-33.9';inputs[1].value='151.2';clickText('保存位置');assert(w.document.getElementById('place').textContent.includes('-33.90'));
click('later');assert.notEqual(w.document.getElementById('time').textContent,'◷ 现在');click('time');clickText('返回现在');assert.equal(w.document.getElementById('time').textContent,'◷ 现在');click('night');assert(w.document.body.classList.contains('red'));click('tonight');assert(text().includes('实际可见性'));assert(text().includes('暗夜时段'));clickText('查看此刻可见天体');assert.equal(w.document.getElementById('sheetTitle').textContent,'此刻可见');click('help');assert(text().includes('相机 AR 为实验性'));
click('track');assert(w.document.getElementById('toast').textContent.includes('安卓 App'));
assert(w.document.getElementById('grid').classList.contains('active'));click('grid');assert(!w.document.getElementById('grid').classList.contains('active'));click('grid');assert(w.document.getElementById('grid').classList.contains('active'));
// Validate Canvas execution and sensor callbacks in the same application scope.
require('node:vm').runInContext('render(); nativeLocation(0,0); tracking=true; nativePose([1,0,0,0,0,-1,0,1,0],0); render(); nativeUnavailable();',dom.getInternalVMContext());
assert.equal(w.document.getElementById('mode').textContent,'自由探索');
click('ar');assert(w.document.getElementById('toast').textContent.includes('新版安卓'));
let camera=false,exported=null;w.NativeSky={setCoordinates(){},track(){},camera(v){camera=v;},exportNotes(s){exported=s;},importNotes(){}};
click('later');click('ar');clickText('开启相机 AR');assert(camera);
const run=s=>require('node:vm').runInContext(s,dom.getInternalVMContext());
run('nativeCameraReady(48);render();');assert(w.document.body.classList.contains('ar'));assert.equal(w.document.getElementById('time').textContent,'◷ 现在');
// Simulate a device rotation without recreating the WebView: target/time remain intact.
run("selected=byId.get('conOri');offset=0;");
Object.defineProperty(w,'innerWidth',{configurable:true,value:760});Object.defineProperty(w,'innerHeight',{configurable:true,value:360});
w.dispatchEvent(new w.Event('resize'));run('nativeCameraReady(62);render();');
assert.equal(w.document.getElementById('sky').width,760);assert.equal(w.document.getElementById('sky').height,360);
assert.equal(run('selected.id'),'conOri');assert.equal(run('fov'),62);
click('calibrate');let range=body().querySelector('input');range.value='1.2';range.dispatchEvent(new w.Event('input'));assert.equal(JSON.parse(w.localStorage.getItem('calibration')).scale,1.2);
run("nativeCameraStopped('相机不可用');");assert(!w.document.body.classList.contains('ar'));assert(!camera);
run('tracking=true; nativePose([1,0,0,0,0,-1,0,1,0],0);nativeSensorAccuracy(0);');assert(w.document.getElementById('mode').textContent.includes('方向待校准'));assert(!w.document.getElementById('calibrate').hidden);
run('fov=85; calibration.az=180; calibration.alt=30;nativePose([1,0,0,0,0,-1,0,1,0],0);render();');
assert.equal(run('az'),0);assert(Math.abs(run('alt'))<1e-9);assert.equal(run('fov'),85);
click('calibrate');assert(text().includes('无需指定东南西北'));assert.equal(body().querySelectorAll('input').length,0);run('tracking=false; sync();');
click('saved');clickText('导出备份');assert.equal(JSON.parse(exported).app,'Starlight');
run(`nativeImportNotes(JSON.stringify({app:'Starlight',version:1,notes:{Moon:'月球观测'}}));`);assert.equal(JSON.parse(w.localStorage.getItem('notes')).Moon,'月球观测');
run(`nativeImportNotes(JSON.stringify({app:'Starlight',version:1,notes:{Moon:'不应覆盖'}}));`);assert.equal(JSON.parse(w.localStorage.getItem('notes')).Moon,'月球观测');
click('tonight');clickText('月相日历');assert.equal(w.document.getElementById('sheetTitle').textContent,'月相日历');assert.equal(body().querySelectorAll('.planner-card').length,8);
let dateInput=body().querySelector('input');dateInput.value='2026-12-30';clickText('查询月相');assert(text().includes('2027'));dateInput=body().querySelector('input');dateInput.value='';clickText('查询月相');assert(w.document.getElementById('toast').textContent.includes('有效日期'));
clickText('查看此时月亮');assert.equal(run('selected.id'),'Moon');assert.equal(run('tracking'),false);assert(!w.document.getElementById('sheet').open);assert.notEqual(w.document.getElementById('time').textContent,'◷ 现在');
click('time');clickText('返回现在');assert.equal(w.document.getElementById('time').textContent,'◷ 现在');
run('tracking=false; nativeReady();');assert.equal(run('tracking'),true);assert(w.document.getElementById('mode').textContent.includes('正在获取'));run('nativePose([1,0,0,0,0,-1,0,1,0],0);');assert(!w.document.getElementById('mode').textContent.includes('正在获取'));
run("selected={name:'目标',v:SkyMath.vec(70,0),alt:10,az:70};render();");assert(w.document.getElementById('target').textContent.includes('屏幕右'));assert.equal(w.document.getElementById('guide').hidden,false);
run('selected.v=SkyMath.vec(0,0);dirty=true;render();');assert(w.document.getElementById('target').textContent.includes('已对准'));assert.equal(w.document.getElementById('guide').hidden,true);
run('selected.alt=-5;dirty=true;render();');assert(w.document.getElementById('target').textContent.includes('地平线下'));
run('tracking=false; selected=starsByMagnitude.find(s=>s.mag>6);az=selected.az;alt=selected.alt;fov=85;dirty=true;render();');assert(run('hit.some(p=>p.s===selected)'));
dom.window.close();console.log('PASS: search, details, persistent notes, coordinate validation, time, night mode, visible list, renderer and missing-sensor fallback.');
