// DOM-level smoke test. No actual rendering, Android sensors or browser emulation.
const {JSDOM}=require('jsdom'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'../app/src/main/assets');
const dom=new JSDOM(fs.readFileSync(path.join(root,'index.html'),'utf8'),{url:'https://app.starlight.local/',runScripts:'outside-only'});
const w=dom.window;
w.HTMLCanvasElement.prototype.getContext=()=>new Proxy({createLinearGradient:()=>({addColorStop(){}}),createRadialGradient:()=>({addColorStop(){}}),measureText:t=>({width:t.length*10})},{get:(o,k)=>k in o?o[k]:()=>{}});
w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};
w.requestAnimationFrame=()=>{};w.cancelAnimationFrame=()=>{};w.setInterval=()=>{};
Object.defineProperty(w.document,'hidden',{configurable:true,value:false});
w.matchMedia=()=>({matches:true,addEventListener(){},removeEventListener(){}});
for(const f of ['astronomy.js','iss.js',...fs.readdirSync(root).filter(f=>/^stars-\d+\.js$/.test(f)).sort(),'messier.js','constellations.js','core.js','camera-view.js','pose.js','visual.js','labels.js','grid.js','backup.js','planner.js','art-data.js','art.js','moon-surface.js','moon-features-data.js','moon-features.js','saturn-surface.js','sun-surface.js','deep-photo.js','photo-view.js','milky-way.js','galaxy.js','app.js'])require('node:vm').runInContext(fs.readFileSync(path.join(root,f),'utf8'),dom.getInternalVMContext());
assert.equal(w.SkyMilky.sprite(0,false),w.SkyMilky.sprite(0,false),'cloud texture is reused during redraw');
const click=id=>w.document.getElementById(id).click(),body=()=>w.document.getElementById('sheetBody'),text=()=>body().textContent;
function clickText(t){const b=[...body().querySelectorAll('button')].find(x=>x.textContent===t);assert(b,t);b.click();}
click('search');let search=body().querySelector('input');search.value='天狼星';search.dispatchEvent(new w.Event('input'));assert(text().includes('天狼星'));clickText('查看');assert(text().includes('光年'));body().querySelector('textarea').value='测试笔记';clickText('收藏并保存笔记');click('saved');assert(text().includes('天狼星'));
click('search');search=body().querySelector('input');search.value='M31';search.dispatchEvent(new w.Event('input'));assert(text().includes('仙女座星系'));clickText('查看');assert(text().includes('目录总星等'));assert(text().includes('NGC 224'));assert(text().includes('未收录'));assert(text().includes('GALEX 紫外合成图'));assert(body().querySelector('img.deep-photo').src.endsWith('/deepsky/m31.jpg'));click('search');search=body().querySelector('input');search.value='NGC1976';search.dispatchEvent(new w.Event('input'));assert(text().includes('猎户座大星云'));clickText('查看');assert(text().includes('Spitzer 红外合成图'));assert(body().querySelector('img.deep-photo').src.endsWith('/deepsky/m42.jpg'));click('search');search=body().querySelector('input');search.value='M8';search.dispatchEvent(new w.Event('input'));clickText('查看');assert(body().querySelector('img.deep-photo').src.endsWith('/deepsky/m8.jpg'));click('search');search=body().querySelector('input');search.value='M33';search.dispatchEvent(new w.Event('input'));clickText('查看');assert(body().querySelector('img.deep-photo').src.endsWith('/deepsky/m33.jpg'));click('search');clickText('浏览梅西耶 110');assert.equal(body().querySelectorAll('.row').length,110);
// The photograph viewer loads the full source and returns to the same object's details.
click('search');search=body().querySelector('input');search.value='M31';search.dispatchEvent(new w.Event('input'));clickText('查看');clickText('查看观测图细节');
const photoViewport=body().querySelector('.deep-viewport'),viewPhoto=photoViewport.querySelector('img');
assert(viewPhoto.src.endsWith('/deepsky/m31.jpg'));assert(viewPhoto.hidden);assert([...body().querySelectorAll('.moon-controls button')].every(b=>b.disabled));
photoViewport.getBoundingClientRect=()=>({left:0,top:0,width:400,height:300});
Object.defineProperties(viewPhoto,{naturalWidth:{value:960},naturalHeight:{value:715}});viewPhoto.onload();assert(!viewPhoto.hidden);assert(text().includes('1.0×'));
const fittedWidth=parseFloat(viewPhoto.style.width);clickText('＋');assert(parseFloat(viewPhoto.style.width)>fittedWidth);assert(text().includes('1.3×'));
const centeredTransform=viewPhoto.style.transform;photoViewport.onpointerdown({pointerId:1,clientX:200,clientY:150,preventDefault(){}});photoViewport.onpointermove({pointerId:1,clientX:230,clientY:150,preventDefault(){}});assert.notEqual(viewPhoto.style.transform,centeredTransform);photoViewport.onpointerup({pointerId:1});
clickText('复位');assert.equal(parseFloat(viewPhoto.style.width),fittedWidth);clickText('返回天体资料');assert(body().querySelector('img.deep-photo'));assert.equal(viewPhoto.onload,null,'departing the viewer removes late load callbacks');
click('search');search=body().querySelector('input');search.value='M42';search.dispatchEvent(new w.Event('input'));clickText('查看');clickText('查看观测图细节');body().querySelector('.deep-viewport img').onerror();assert(text().includes('图片加载失败'));click('close');
click('search');clickText('浏览 88 星座');assert.equal(body().querySelectorAll('.row').length,88);
click('search');search=body().querySelector('input');search.value='六分';search.dispatchEvent(new w.Event('input'));assert(text().includes('六分儀座'));clickText('查看');assert(text().includes('没有收录连线'));clickText('在星图中定位');assert.equal(require('node:vm').runInContext('selected.id',dom.getInternalVMContext()),'conSex');
click('search');search=body().querySelector('input');search.value='巨蛇座';search.dispatchEvent(new w.Event('input'));assert.equal([...body().querySelectorAll('.row b')].filter(x=>x.textContent==='巨蛇座').length,1);
click('loc');let inputs=body().querySelectorAll('input');inputs[0].value='91';inputs[1].value='0';clickText('保存位置');assert(w.document.getElementById('toast').textContent.includes('有效纬度'));inputs[0].value='-33.9';inputs[1].value='151.2';clickText('保存位置');assert(w.document.getElementById('place').textContent.includes('-33.90'));
click('later');assert.notEqual(w.document.getElementById('time').textContent,'◷ 现在');click('time');clickText('返回现在');assert.equal(w.document.getElementById('time').textContent,'◷ 现在');click('night');assert(w.document.body.classList.contains('red'));click('tonight');assert(text().includes('实际可见性'));assert(text().includes('暗夜时段'));clickText('查看此刻可见天体');assert.equal(w.document.getElementById('sheetTitle').textContent,'此刻可见');click('help');assert(text().includes('相机 AR 为实验性'));
click('track');assert(w.document.getElementById('toast').textContent.includes('安卓 App'));
assert(!w.document.getElementById('grid').classList.contains('active'));click('grid');assert(w.document.getElementById('grid').classList.contains('active'));click('grid');assert(!w.document.getElementById('grid').classList.contains('active'));
click('help');clickText('开启真实昼夜大气');assert.equal(JSON.parse(w.localStorage.getItem('config')).atmosphere,true);clickText('关闭昼夜大气 · 展示完整星图');assert.equal(JSON.parse(w.localStorage.getItem('config')).atmosphere,false);
clickText('隐藏银河摄影');assert.equal(JSON.parse(w.localStorage.getItem('config')).galaxy,false);clickText('显示银河摄影');assert.equal(JSON.parse(w.localStorage.getItem('config')).galaxy,true);assert(text().includes('ESO/S. Brunier'));
const artStrength=body().querySelector('#artStrength');assert(artStrength);artStrength.value='45';artStrength.dispatchEvent(new w.Event('input'));artStrength.dispatchEvent(new w.Event('change'));assert.equal(JSON.parse(w.localStorage.getItem('config')).artStrength,.45);assert(text().includes('插画亮度 · 45%'));clickText('隐藏星座插画');assert(body().querySelector('#artStrength').disabled);clickText('显示星座插画');assert(!body().querySelector('#artStrength').disabled);
// Validate Canvas execution and sensor callbacks in the same application scope.
require('node:vm').runInContext('render(); nativeLocation(0,0); tracking=true; nativePose([1,0,0,0,0,-1,0,1,0],0); render(); nativeUnavailable();',dom.getInternalVMContext());
assert.equal(w.document.getElementById('mode').textContent,'自由探索');
click('ar');assert(w.document.getElementById('toast').textContent.includes('新版安卓'));
let camera=false,exported=null,checks=0,downloads=0,installs=0,weatherCoords=null,issFetches=0;w.NativeSky={setCoordinates(){},track(){},camera(v){camera=v;},exportNotes(s){exported=s;},importNotes(){},checkUpdate(){checks++},downloadUpdate(){downloads++},installUpdate(){installs++},hasVerifiedUpdate(){return false},fetchWeather(lat,lon){weatherCoords=[lat,lon]},fetchIss(){issFetches++}};
click('later');click('ar');clickText('开启相机 AR');assert(camera);
const run=s=>require('node:vm').runInContext(s,dom.getInternalVMContext());
run('nativeCameraReady(48,0);render();');assert(w.document.body.classList.contains('ar'));assert.equal(w.document.getElementById('time').textContent,'◷ 现在');
// Simulate a device rotation without recreating the WebView: target/time remain intact.
run("selected=byId.get('conOri');offset=0;");
Object.defineProperty(w,'innerWidth',{configurable:true,value:760});Object.defineProperty(w,'innerHeight',{configurable:true,value:360});
w.dispatchEvent(new w.Event('resize'));run('nativeCameraReady(62,1);render();');
assert.equal(w.document.getElementById('sky').width,760);assert.equal(w.document.getElementById('sky').height,360);
assert.equal(run('selected.id'),'conOri');assert.equal(run('fov'),62);
click('calibrate');let range=body().querySelector('input');range.value='1.2';range.dispatchEvent(new w.Event('input'));assert.equal(JSON.parse(w.localStorage.getItem('calibration')).scale,1.2);assert(text().includes('估计'));assert.equal(range.id,'cameraWidthScale');assert.equal(JSON.parse(w.localStorage.getItem('calibration')).space,'tangent');assert(Math.abs(run('fov')-w.SkyCameraView.apply(62,1.2).fov)<1e-9);
run("calibration={az:0,alt:0,scale:1.2,space:'angle'};nativeCameraReady(62,0)");assert(Math.abs(run('fov')-74.4)<1e-9);assert.equal(run('calibration.space'),'tangent');
const migratedScale=run('calibration.scale');run('nativeCameraReady(62,0)');assert.equal(run('calibration.scale'),migratedScale,'legacy calibration migrates once');click('calibrate');assert(text().includes('相机报告参数'));
run('nativeCameraReady(NaN,0)');click('calibrate');assert(text().includes('设备未报告'));clickText('重置相机视场');assert.equal(run('fov'),45);assert.equal(run('calibration.scale'),1);assert.equal(w.localStorage.getItem('calibration'),null);
run("nativeCameraStopped('相机不可用');");assert(!w.document.body.classList.contains('ar'));assert(!camera);
click('search');clickText('🛰 ISS 实时位置');assert.equal(issFetches,1);
run('nativeIssResult(JSON.stringify({latitude:cfg.lat,longitude:cfg.lon,altitude:410,velocity:27500,timestamp:Date.now()}))');assert(text().includes('仰角 90.0°'));clickText('在星图定位此刻快照');assert.equal(run('selected.id'),'ISS');
run('offset=3600000;calculate()');assert.equal(run('selected'),null);run('offset=0');
run("nativeIssError('连接失败')");assert.equal(run('issSnapshot'),null);assert.equal(run('selected'),null);
click('search');clickText('🛰 ISS 实时位置');run('nativeIssResult(JSON.stringify({latitude:cfg.lat,longitude:cfg.lon,altitude:410,velocity:27500,timestamp:Date.now()-30000}))');assert(text().includes('过期'));assert.equal(run('issSnapshot'),null);
run('nativeIssResult(JSON.stringify({latitude:cfg.lat,longitude:cfg.lon,altitude:410,timestamp:Date.now()}));issSnapshot.timestamp-=13000');clickText('在星图定位此刻快照');assert(text().includes('已过期'));assert.equal(run('selected'),null);
run('tracking=true; nativePose([1,0,0,0,0,-1,0,1,0],0);nativeSensorAccuracy(0);');assert(w.document.getElementById('mode').textContent.includes('方向待校准'));assert(!w.document.getElementById('calibrate').hidden);
run('fov=85; calibration.az=180; calibration.alt=30;nativePose([1,0,0,0,0,-1,0,1,0],0);render();');
assert.equal(run('az'),0);assert(Math.abs(run('alt'))<1e-9);assert.equal(run('fov'),85);
click('calibrate');assert(text().includes('无需指定东南西北'));assert.equal(body().querySelectorAll('input').length,0);run('tracking=false; sync();');
click('saved');clickText('导出备份');assert.equal(JSON.parse(exported).app,'Starlight');
run(`nativeImportNotes(JSON.stringify({app:'Starlight',version:1,notes:{Moon:'月球观测'}}));`);assert.equal(JSON.parse(w.localStorage.getItem('notes')).Moon,'月球观测');
run(`nativeImportNotes(JSON.stringify({app:'Starlight',version:1,notes:{Moon:'不应覆盖'}}));`);assert.equal(JSON.parse(w.localStorage.getItem('notes')).Moon,'月球观测');
click('tonight');clickText('月相日历');assert.equal(w.document.getElementById('sheetTitle').textContent,'月相日历');assert.equal(body().querySelectorAll('.planner-card').length,8);
click('tonight');clickText('联网查看云量和降水');clickText('获取未来 24 小时预报');assert.deepEqual(weatherCoords,[run('cfg.lat'),run('cfg.lon')]);
run('nativeWeatherResult(JSON.stringify({latitude:-33.9,longitude:151.2,retrieved:Date.now(),currentTime:Date.now(),cloud:15,precipitation:0,temperature:18,hours:[[Date.now()+3600000,20,10,14000]]}))');assert(text().includes('Open-Meteo'));assert(text().includes('能见度 14.0 km'));
assert(w.localStorage.getItem('weatherForecastV1'));
click('tonight');assert(text().includes('天气辅助观测'));assert(text().includes('获取于'));
click('later');click('tonight');assert(text().includes('现实天气预报不参与'));assert(!text().includes('天气辅助观测'));click('time');clickText('返回现在');click('tonight');
clickText('联网查看云量和降水');
run("nativeWeatherError('连接失败')");assert(text().includes('上次获取的预报（非实时）'));assert(text().includes('能见度 14.0 km'));
run('setPlace(40,116,"新位置")');click('tonight');clickText('联网查看云量和降水');run("nativeWeatherError('连接失败')");assert(text().includes('连接失败'));assert(!text().includes('能见度 14.0 km'));
run('setPlace(-33.9,151.2,"原位置")');const stale=JSON.parse(w.localStorage.getItem('weatherForecastV1'));stale.data.retrieved=Date.now()-4*3600000;w.localStorage.setItem('weatherForecastV1',JSON.stringify(stale));click('tonight');clickText('联网查看云量和降水');run("nativeWeatherError('连接失败')");assert(text().includes('连接失败'));assert(!text().includes('上次获取的预报'));
click('help');clickText('检查更新');clickText('检查新版本');assert(checks>0);
run("nativeUpdateAvailable('0.3.1','0.3.2','1234567')");assert(text().includes('新版 0.3.2'));clickText('下载并验证 0.3.2');assert.equal(downloads,1);
run("nativeUpdateProgress('50')");assert(text().includes('50%'));run("nativeUpdateReady('0.3.2')");clickText('打开系统安装界面');assert.equal(installs,1);
click('tonight');clickText('月相日历');
let dateInput=body().querySelector('input');dateInput.value='2026-12-30';clickText('查询月相');assert(text().includes('2027'));dateInput=body().querySelector('input');dateInput.value='';clickText('查询月相');assert(w.document.getElementById('toast').textContent.includes('有效日期'));
clickText('查看此时月亮');assert.equal(run('selected.id'),'Moon');assert.equal(run('tracking'),false);assert(!w.document.getElementById('sheet').open);assert.notEqual(w.document.getElementById('time').textContent,'◷ 现在');
click('time');clickText('返回现在');assert.equal(w.document.getElementById('time').textContent,'◷ 现在');
run('tracking=false; nativeReady();');assert.equal(run('tracking'),true);assert(w.document.getElementById('mode').textContent.includes('正在获取'));run('nativePose([1,0,0,0,0,-1,0,1,0],0);');assert(!w.document.getElementById('mode').textContent.includes('正在获取'));
run("selected={name:'目标',v:SkyMath.vec(70,0),alt:10,az:70};render();");assert(w.document.getElementById('target').textContent.includes('屏幕右'));assert.equal(w.document.getElementById('guide').hidden,false);
run('selected.v=SkyMath.vec(0,0);dirty=true;render();');assert(w.document.getElementById('target').textContent.includes('已对准'));assert.equal(w.document.getElementById('guide').hidden,true);
run('selected.alt=-5;dirty=true;render();');assert(w.document.getElementById('target').textContent.includes('地平线下'));
run("selected=byId.get('Moon');tracking=false;az=selected.az;alt=selected.alt;dirty=true;render();");assert.equal(run('selected.id'),'Moon');
run('tracking=false; selected=starsByMagnitude.find(s=>s.mag>6);az=selected.az;alt=selected.alt;fov=85;dirty=true;render();');assert(run('hit.nearest(width/2,height/2)===selected'));
run('cfg.art=true;dirty=true;render()');assert(run('artwork.filter(a=>a.image).length<=12'));run('cfg.art=false;dirty=true;render()');assert.equal(run('artwork.filter(a=>a.image).length'),0);
run("details(byId.get('Moon'))");clickText('查看月面细节');assert(body().querySelector('canvas.moon-surface'));assert(text().includes('未模拟天平动'));click('close');
run("let moonDraws=0;Object.defineProperty(moonMap,'complete',{configurable:true,value:true});Object.defineProperty(moonMap,'naturalWidth',{configurable:true,value:2048});SkyMoonSurface.draw=()=>{moonDraws++};tracking=false;az=bodies[1].az;alt=bodies[1].alt;dirty=true;render();dirty=true;render()");
assert.equal(run('moonDraws'),1,'sky-map Moon sprite should reuse a cached phase');
run('bodies[1].phaseAngle+=4;dirty=true;render()');assert.equal(run('moonDraws'),2,'changed phase should redraw the sprite');
// Folding the chrome must retain the target, time, field of view and tracking state.
const viewingState=run('[selected.id,offset,fov,tracking].join("/")');
click('focusMode');assert(w.document.body.classList.contains('sky-focus'));
assert.equal(w.document.getElementById('focusMode').getAttribute('aria-pressed'),'true');
assert.equal(w.document.getElementById('focusMode').textContent,'返回');
run('render()');assert.equal(run('[selected.id,offset,fov,tracking].join("/")'),viewingState);
click('focusMode');assert(!w.document.body.classList.contains('sky-focus'));
assert.equal(w.document.getElementById('focusMode').getAttribute('aria-pressed'),'false');
assert.equal(run('[selected.id,offset,fov,tracking].join("/")'),viewingState);
// Exercise the actual moon viewer handlers with a decoded-image stand-in.
const oldImage=w.Image,oldFrame=w.requestAnimationFrame,oldDraw=w.SkyMoonSurface.draw,oldSunCreate=w.SkySunSurface.create;let viewState=null,viewDraws=0;
w.Image=class {set src(v){if(v&&this.onload)this.onload();}};w.requestAnimationFrame=fn=>{fn();return 1;};
w.SkyMoonSurface.draw=(c,img,phase,view)=>{viewState={...view,size:c.width};viewDraws++;};
w.SkySunSurface.create=(image,renderer)=>({draw(c,view){renderer.draw(c,image,180,view);},release(){},dispose(){}});
run('showMoonSurface()');let surface=body().querySelector('canvas');assert.equal(viewState.zoom,1);
clickText('＋');assert.equal(viewState.zoom,1.25);clickText('切换地形照明');assert.equal(viewState.inspect,true);
surface.onpointerdown({pointerId:1,clientX:100,clientY:100,preventDefault(){}});
surface.onpointermove({pointerId:1,clientX:140,clientY:120});assert(viewState.yaw>0);assert.equal(viewState.size,256);
surface.onpointerup({pointerId:1});assert.equal(viewState.size,512);
surface.onkeydown({key:'0',preventDefault(){}});assert.equal(viewState.zoom,1);assert.equal(viewState.yaw,0);assert.equal(viewState.pitch,0);
clickText('恢复月相照明');assert.equal(viewState.inspect,false);
click('close');const drawsAtClose=viewDraws;surface.onwheel({deltaY:-1,preventDefault(){}});assert.equal(viewDraws,drawsAtClose);
run("details(byId.get('Sun'))");clickText('查看太阳细节');
assert.equal(w.document.getElementById('sheetTitle').textContent,'太阳细节');
assert(text().includes('非实时'));assert(text().includes('Solar System Scope'));assert.equal(viewState.emissive,true);
assert.equal(viewState.glow,true);clickText('隐藏光晕');assert.equal(viewState.glow,false);
clickText('＋');assert.equal(viewState.zoom,1.25);clickText('复位');assert.equal(viewState.zoom,1);
click('close');
run("details(byId.get('Jupiter'))");clickText('查看木星大气');
assert.equal(w.document.getElementById('sheetTitle').textContent,'木星大气');
assert(text().includes('非实时'));assert(text().includes('Solar System Scope'));
assert.equal(viewState.inspect,true);assert.equal(viewState.emissive,false);
clickText('＋');assert.equal(viewState.zoom,1.25);
let jovian=body().querySelector('canvas');jovian.onpointerdown({pointerId:1,clientX:120,clientY:100,preventDefault(){}});
jovian.onpointermove({pointerId:1,clientX:160,clientY:100});assert(viewState.yaw>0);
jovian.onpointerup({pointerId:1});assert.equal(viewState.size,512);
click('close');
const oldSaturnDraw=w.SkySaturn.draw;let saturnState=null,saturnDraws=0;
w.SkySaturn.draw=(c,img,view)=>{saturnState={...view,size:c.width};saturnDraws++;};
run("details(byId.get('Saturn'))");clickText('查看土星和光环');
assert.equal(w.document.getElementById('sheetTitle').textContent,'土星和光环');
assert(text().includes('非实时'));assert(text().includes('Solar System Scope'));
assert(text().includes('光环开口、朝向'));assert.equal(saturnState.zoom,1);
clickText('＋');assert.equal(saturnState.zoom,1.25);
let saturn=body().querySelector('canvas');saturn.onpointerdown({pointerId:1,clientX:120,clientY:100,preventDefault(){}});
saturn.onpointermove({pointerId:1,clientX:160,clientY:120});assert(saturnState.yaw>0);assert(saturnState.pitch>0);
saturn.onpointerup({pointerId:1});assert.equal(saturnState.size,512);
click('close');
run("Object.defineProperty(saturnMap,'complete',{configurable:true,value:true});Object.defineProperty(saturnMap,'naturalWidth',{configurable:true,value:2048})");
const afterViewer=saturnDraws;
run("tracking=false;az=byId.get('Saturn').az;alt=Math.max(-85,byId.get('Saturn').alt);dirty=true;render();dirty=true;render()");
assert.equal(saturnDraws,afterViewer+1,'the main chart should reuse one cached ringed marker');
w.SkySaturn.draw=oldSaturnDraw;
w.Image=oldImage;w.requestAnimationFrame=oldFrame;w.SkyMoonSurface.draw=oldDraw;w.SkySunSurface.create=oldSunCreate;
// Main-chart gestures use the same projection as the renderer and retain
// selected targets after pinching, cancelling or lifting either finger first.
const sky=w.document.getElementById('sky'),pointer=(pointerId,clientX,clientY)=>({pointerId,clientX,clientY,button:0});
sky.setPointerCapture=()=>{};
run('clearSkyPointers();tracking=false;ar=false;az=359;alt=15;roll=0;fov=85;selected=byId.get("Moon");hit.clear();hit.add(byId.get("Sun"),450,190);');
run('var gestureRay=M.unproject(300,180,M.basis(az,alt),width,height,fov);');
sky.onpointerdown(pointer(1,250,180));sky.onpointerdown(pointer(2,350,180));sky.onpointermove(pointer(2,450,180));
let projected=run('M.project(gestureRay,M.basis(az,alt),width,height,fov)');
assert(Math.abs(projected[0]-350)<1e-6);assert(Math.abs(projected[1]-180)<1e-6);assert(run('fov<85'));
const pinchView=run('[az,alt,fov].join("/")');sky.onpointerup(pointer(1,250,180));
sky.onpointermove(pointer(2,460,190));assert.notEqual(run('[az,alt,fov].join("/")'),pinchView);
sky.onpointerup(pointer(2,460,190));assert.equal(run('selected.id'),'Moon','pinch must not pick another object');
for(const first of [1,2]){
 sky.onpointerdown(pointer(1,350,190));sky.onpointerdown(pointer(2,450,190));
 sky.onpointerup(pointer(first,first===1?350:450,190));sky.onpointerup(pointer(first===1?2:1,first===1?450:350,190));
 assert.equal(run('selected.id'),'Moon','even a stationary two-finger gesture is not a tap');
}
sky.onpointerdown(pointer(1,450,190));sky.onpointerup(pointer(1,450,190));assert.equal(run('selected.id'),'Sun','single tap still selects');
sky.onpointerdown(pointer(1,450,190));sky.onpointercancel(pointer(1,450,190));sky.onpointerup(pointer(1,450,190));assert.equal(run('selected.id'),'Sun');assert.equal(run('pointers.size'),0);
sky.onpointerdown(pointer(1,100,100));sky.onlostpointercapture({pointerId:1});assert.equal(run('pointers.size'),0);
sky.onpointerdown(pointer(1,100,100));w.dispatchEvent(new w.Event('blur'));assert.equal(run('pointers.size'),0);
sky.onpointerdown(pointer(1,100,100));w.dispatchEvent(new w.Event('resize'));assert.equal(run('pointers.size'),0);
// Third fingers are ignored until exactly one or two pointers remain.
sky.onpointerdown(pointer(1,100,100));sky.onpointerdown(pointer(2,200,100));sky.onpointerdown(pointer(3,300,100));
const threeView=run('[az,alt,fov].join("/")');sky.onpointermove(pointer(3,400,200));assert.equal(run('[az,alt,fov].join("/")'),threeView);
sky.onpointerup(pointer(3,400,200));sky.onpointermove(pointer(2,220,100));assert.notEqual(run('[az,alt,fov].join("/")'),threeView);
sky.onpointerup(pointer(2,220,100));sky.onpointerup(pointer(1,100,100));assert.equal(run('selected.id'),'Sun');
// A free-map wheel zoom anchors the cursor; a tracking zoom keeps direction.
run('tracking=false;az=359;alt=15;fov=85;gestureRay=M.unproject(430,180,M.basis(az,alt),width,height,fov);');
sky.onwheel({clientX:430,clientY:180,deltaY:-1,preventDefault(){}});
projected=run('M.project(gestureRay,M.basis(az,alt),width,height,fov)');assert(Math.abs(projected[0]-430)<1e-6);assert(Math.abs(projected[1]-180)<1e-6);
run('tracking=true;');const direction=run('[az,alt].join("/")');sky.onwheel({clientX:430,clientY:180,deltaY:-1,preventDefault(){}});assert.equal(run('[az,alt].join("/")'),direction);assert.equal(run('tracking'),true);
click('zoomIn');assert.equal(run('tracking'),true);assert.equal(run('[az,alt].join("/")'),direction);
// Sensor-mode taps retain tracking; deliberate drag enters free exploration.
sky.onpointerdown(pointer(1,450,190));sky.onpointerup(pointer(1,450,190));assert.equal(run('tracking'),true);
sky.onpointerdown(pointer(1,100,100));sky.onpointermove(pointer(1,130,120));sky.onpointerup(pointer(1,130,120));assert.equal(run('tracking'),false);
// Camera AR must retain its measured field of view through map gestures.
run('ar=true;tracking=true;fov=48;');const arView=run('[az,alt,fov,tracking].join("/")');
sky.onpointerdown(pointer(1,100,100));sky.onpointerdown(pointer(2,200,100));sky.onpointermove(pointer(2,240,130));sky.onpointerup(pointer(1,100,100));sky.onpointerup(pointer(2,240,130));
sky.onwheel({clientX:430,clientY:180,deltaY:-1,preventDefault(){}});click('zoomIn');assert.equal(run('[az,alt,fov,tracking].join("/")'),arView);run('ar=false;tracking=false;');
// Density is taken from the actual chart buffer, including its pixel budget.
const originalPhotoSprite=w.SkyDeepPhoto.sprite,originalArtDraw=w.SkyArt.draw,originalArtRelease=w.SkyArt.release;
let requestedPixels=[],artRatios=[],artReleases=0;
w.SkyDeepPhoto.sprite=(image,need)=>{requestedPixels.push(need);return {width:image.naturalWidth,height:image.naturalHeight};};
Object.defineProperty(w,'devicePixelRatio',{configurable:true,value:3});w.dispatchEvent(new w.Event('resize'));
run('deepPhotoImages.set("M31",{complete:true,naturalWidth:960,naturalHeight:715});deepPhotoImages.set("M42",{complete:true,naturalWidth:800,naturalHeight:1875});deepPhoto("M31",170);deepPhoto("M42",100);');
assert.equal(requestedPixels[0],510);assert.equal(requestedPixels[1],703.125,'tall photos need density for the longer axis');
w.SkyArt.draw=(...args)=>{artRatios.push(args[6]);};w.SkyArt.release=()=>{artReleases++;originalArtRelease();};
run('for(const a of artwork)a.image={complete:true,naturalWidth:512};cfg.art=true;dirty=true;render();');
assert(artRatios.length>0);assert(artRatios.every(r=>r===run('canvas.width/width')));
run('cfg.art=false;dirty=true;render();');assert(artReleases>0,'hiding art releases its extra buffer');
w.SkyDeepPhoto.sprite=originalPhotoSprite;w.SkyArt.draw=originalArtDraw;w.SkyArt.release=originalArtRelease;
dom.window.close();console.log('PASS: search, details, persistent notes, coordinate validation, time, night mode, visible list, renderer and missing-sensor fallback.');
